version: "2.0"

services:
  sbazar-scraper:
    build: .
    depends_on:
      - mysql
    env_file: .env
    command: ./bin/scraper scrape sbazar

  aukro:
      build: .
      depends_on:
        - mysql
      env_file: .env
      command: ./bin/scraper scrape aukro

  mysql:
      image: mysql:5.7
      container_name: bazaar.dev
      env_file:
        - ./.docker/db/db.env
      volumes:
        - ./.docker/db/:/docker-entrypoint-initdb.d
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
      ports:
        - 3307:3306
