version: "3.6"

services:
  sbazar:
    build:
      context: .
      dockerfile: .docker/dockerfile.php.cli
    container_name: sbazar.dev
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - .:/scraper
    command: ./bin/scraper scrape s-bazar

  cyklobazar:
      build:
        context: .
        dockerfile: .docker/dockerfile.php.cli
      container_name: cyklobazar.dev
      depends_on:
        - mysql
      env_file: .env
      volumes:
        - .:/scraper
      command: ./bin/scraper scrape cyklo-bazar

  mysql:
      image: mysql:5.7
      container_name: bazaar.dev
      env_file:
        - .docker/db/db.env
      volumes:
        - .docker/db/:/docker-entrypoint-initdb.d
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
      ports:
        - 3307:3306
