version: "3.6"

services:
  scraper:
    build:
      context: .
      dockerfile: .docker/dockerfile.php.cli
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - .:/scraper
    entrypoint: ["sh", "/scraper/.docker/scraper/entrypoint.sh"]
